services:
  expression:
    image: docker/symai-expression.0.0.1
    container_name: symai-expression.0.0.1
    build:
      context: ../python/server
      dockerfile: ../../docker/Expression
    ports:
      - 8080:8080
    working_dir: /app
    network_mode: host
    volumes:
        - ${PROPERTIES}:/properties
        - ${LOGDIR}:/logdir
        - ${TMPDIR}:/tmpdir
  core_go:
    image: docker/symai-core_go.0.0.1
    container_name: symai-core_go.0.0.1
    build:
      context: ../../
      dockerfile:  ./src/docker/SymAICore_go
    ports:
      - 12345:12345
    working_dir: /app
    network_mode: host
    volumes:
        - ${PROPERTIES}:/properties
        - ${LOGDIR}:/logdir
        - ${TMPDIR}:/tmpdir
  frontend_go:
    image: docker/symai-front_go.0.0.1
    container_name: symai-front_go.0.0.1
    build:
      context: ../../
      dockerfile:  ./src/docker/Frontend_go
    ports:
      - 8000:8000
    working_dir: /app
    network_mode: host
    volumes:
      - ${PROPERTIES}:/properties
      - ${LOGDIR}:/logdir
      - ${TMPDIR}:/tmpdir

